name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Generate pacman SVG
      uses: abozanona/pacman-contribution-graph@main
      with:
        github_user_name: ${{ github.repository_owner }}
  
    - name: Create output folder and move SVGs
      run: |
        mkdir -p output
        mv dist/pacman-contribution-graph.svg output/
        mv dist/pacman-contribution-graph-dark.svg output/
      
    - name: Push to output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: output
        build_dir: output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

